name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Main profile metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: appleweiping
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin

      - name: Coding habits chart
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: appleweiping
          template: classic
          base: ""
          config_timezone: Europe/Berlin
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes

      - name: Language activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: appleweiping
          template: classic
          base: ""
          config_timezone: Europe/Berlin
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
